# Generated by Django 6.0.6 on 2026-06-11 17:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('marca', models.CharField(blank=True, default='', max_length=100, verbose_name='Marca')),
                ('quantidade', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('unidade', models.CharField(choices=[('g', 'Gramas'), ('mL', 'Mililitros'), ('kit', 'Kit'), ('kg', 'Quilogramas'), ('un.', 'Unidades')], default='g', max_length=10, verbose_name='Unidade')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('localizacao_local', models.CharField(blank=True, default='', max_length=100, verbose_name='Local')),
                ('localizacao_prateleira', models.CharField(blank=True, default='', max_length=50, verbose_name='Prateleira')),
                ('localizacao_setor', models.CharField(blank=True, default='', max_length=100, verbose_name='Setor')),
                ('data_verificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Verificação')),
                ('usuario_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Reagente',
                'verbose_name_plural': 'Reagentes',
                'ordering': ['data_validade'],
            },
        ),
    ]
